[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32@7.0.1
board = esp32dev
framework = arduino
board_build.partitions = partitions.csv
lib_extra_dirs = ../shared
build_flags = -std=gnu++17 -DDMS_ROLE_MASTER=1
monitor_speed = 115200

[env:native]
platform = native
test_framework = unity
build_flags = -std=gnu++17
lib_extra_dirs = ../shared
lib_compat_mode = off
