#include <unity.h>
#include <cstring>
#include <BmsSnapshot.h>
#include <BinaryLogger.h>
#include <DmsLink.h>
#include <JbdCodec.h>
#include <LogFormat.h>
#include <RegisterBank.h>
#include <RtcClock.h>
#include <StorageConfig.h>
using namespace dms;
static JbdFrame response(uint8_t cmd,const uint8_t*p,uint8_t n,uint8_t status=0){JbdFrame f{};f.bytes[0]=0xDD;f.bytes[1]=cmd;f.bytes[2]=status;f.bytes[3]=n;memcpy(f.bytes+4,p,n);uint16_t c=jbdChecksum(f.bytes+2,n+2);f.bytes[n+4]=c>>8;f.bytes[n+5]=c;f.bytes[n+6]=0x77;f.size=n+7;f.command=cmd;f.status=status;f.payloadLength=n;return f;}
void requests(){const uint8_t expected[][7]={{0xDD,0xA5,3,0,0xFF,0xFD,0x77},{0xDD,0xA5,4,0,0xFF,0xFC,0x77},{0xDD,0xA5,5,0,0xFF,0xFB,0x77}};uint8_t b[7];for(int i=0;i<3;i++){TEST_ASSERT_EQUAL(7,encodeJbdRead(i+3,b,7));TEST_ASSERT_EQUAL_UINT8_ARRAY(expected[i],b,7);}}
void basic(){uint8_t p[28]{};p[0]=0x13;p[1]=0x88;p[2]=0xF8;p[3]=0x24;p[4]=0x01;p[5]=0xF4;p[6]=0x03;p[7]=0xE8;p[10]=0x20;p[11]=0x68;p[18]=0x21;p[19]=80;p[21]=24;p[22]=1;p[23]=0x0B;p[24]=0xA5;p[25]=0xAA;p[26]=0x77;p[27]=0;BasicInfo b;auto f=response(3,p,sizeof p);TEST_ASSERT_TRUE(decodeBasic(f,b));TEST_ASSERT_EQUAL_INT32(-20120,b.current_mA);TEST_ASSERT_EQUAL_UINT32(5000,b.remaining_mAh);TEST_ASSERT_EQUAL(2016,b.year);TEST_ASSERT_EQUAL(3,b.month);TEST_ASSERT_EQUAL(8,b.day);TEST_ASSERT_EQUAL_INT16(250,b.temperatures_dC[0]);TEST_ASSERT_EQUAL(3,b.extraLength);}
void cells_reset(){uint8_t p[48];for(int i=0;i<24;i++){uint16_t v=3300+i;p[2*i]=v>>8;p[2*i+1]=v;}CellInfo c;c.maximum_mV=65535;c.maxIndex=99;auto f=response(4,p,48);TEST_ASSERT_TRUE(decodeCells(f,c));TEST_ASSERT_EQUAL(24,c.count);TEST_ASSERT_EQUAL(1,c.minIndex);TEST_ASSERT_EQUAL(24,c.maxIndex);TEST_ASSERT_EQUAL(23,c.delta_mV);uint8_t p2[]={0x0C,0xE4,0x0C,0xE5};f=response(4,p2,4);TEST_ASSERT_TRUE(decodeCells(f,c));TEST_ASSERT_EQUAL(2,c.count);TEST_ASSERT_EQUAL(1,c.delta_mV);}
void hardware(){const uint8_t p[]={'S','P','2','4','S'};auto f=response(5,p,sizeof p);char h[32];TEST_ASSERT_TRUE(decodeHardware(f,h,sizeof h));TEST_ASSERT_EQUAL_STRING("SP24S",h);}
void invalid_frames(){uint8_t p[]={1,2};auto f=response(4,p,2);JbdFrame out;TEST_ASSERT_EQUAL_INT((int)JbdResult::OK,(int)validateJbdResponse(f.bytes,f.size,4,&out));f.bytes[5]^=1;TEST_ASSERT_EQUAL_INT((int)JbdResult::BAD_CHECKSUM,(int)validateJbdResponse(f.bytes,f.size,4));TEST_ASSERT_EQUAL_INT((int)JbdResult::INCOMPLETE,(int)validateJbdResponse(f.bytes,3,4));auto e=response(4,p,2,0x80);TEST_ASSERT_EQUAL_INT((int)JbdResult::BAD_STATUS,(int)validateJbdResponse(e.bytes,e.size,4));}
void link(){TEST_ASSERT_EQUAL_HEX16(0x29B1,crc16Ccitt((const uint8_t*)"123456789",9));uint8_t raw[256],enc[300],dec[256];for(int i=0;i<256;i++)raw[i]=i;size_t n=cobsEncode(raw,256,enc,sizeof enc),z=cobsDecode(enc,n,dec,sizeof dec);TEST_ASSERT_EQUAL(256,z);TEST_ASSERT_EQUAL_UINT8_ARRAY(raw,dec,256);LinkFrame a;a.type=PING;a.transactionId=0x1234;a.length=4;memcpy(a.payload,"abc",4);uint8_t w[512];n=encodeLink(a,w,sizeof w);LinkFrame b;TEST_ASSERT_TRUE(decodeLink(w,n,b));TEST_ASSERT_EQUAL_HEX16(a.transactionId,b.transactionId);w[2]^=1;TEST_ASSERT_FALSE(decodeLink(w,n,b));}
void snapshot_wire(){BmsSnapshot s;s.sequence=42;s.timestampUtcMs=1700000000000ULL;s.basic.voltage_mV=80000;s.basic.current_mA=-1200;s.basic.power_mW=-96000;s.basic.remaining_mAh=50000;s.basic.nominal_mAh=100000;s.cells.count=2;s.cells.mV[0]=3300;s.cells.mV[1]=3310;s.basic.ntcCount=1;s.basic.temperatures_dC[0]=250;uint8_t b[200];size_t n=serializeSample(s,77,b,sizeof b);BmsSnapshot o;uint32_t age;TEST_ASSERT_TRUE(deserializeSample(b,n,o,age));TEST_ASSERT_EQUAL(42,o.sequence);TEST_ASSERT_EQUAL(77,age);TEST_ASSERT_EQUAL_INT32(-1200,o.basic.current_mA);TEST_ASSERT_EQUAL(3310,o.cells.mV[1]);SnapshotStore store;store.publish(s);BmsSnapshot copy;TEST_ASSERT_TRUE(store.latest(copy));TEST_ASSERT_EQUAL(42,copy.sequence);}
void rtc_epoch(){DateTime d{2024,2,29,23,59,58},o{};TEST_ASSERT_TRUE(validDate(d));uint64_t e=dateToEpochMs(d);TEST_ASSERT_TRUE(epochMsToDate(e,o));TEST_ASSERT_EQUAL(d.year,o.year);TEST_ASSERT_EQUAL(d.month,o.month);TEST_ASSERT_EQUAL(d.day,o.day);DateTime bad{2023,2,29,0,0,0};TEST_ASSERT_FALSE(validDate(bad));}
void log_record(){uint8_t p[]={1,2,3},r[32];size_t n=encodeLogRecord(LogType::SYSTEM_EVENT,1,p,3,r,sizeof r);TEST_ASSERT_EQUAL(15,n);uint32_t got=r[n-4]|uint32_t(r[n-3])<<8|uint32_t(r[n-2])<<16|uint32_t(r[n-1])<<24;TEST_ASSERT_EQUAL_HEX32(crc32(r,n-4),got);}
void log_header(){uint8_t h[64]{};memcpy(h,"DMSLOG2",7);h[7]=2;uint8_t*p=h+60;put32(p,crc32(h,60));TEST_ASSERT_TRUE(validLogHeader(h,sizeof h));h[20]^=1;TEST_ASSERT_FALSE(validLogHeader(h,sizeof h));}
void log_storage_policy(){TEST_ASSERT_FALSE(logNeedsRotation(0,LOG_ROTATE_BYTES+1));TEST_ASSERT_FALSE(logNeedsRotation(LOG_ROTATE_BYTES-12,12));TEST_ASSERT_TRUE(logNeedsRotation(LOG_ROTATE_BYTES-11,12));TEST_ASSERT_TRUE(logHasReserve(128*1024,64*1024));TEST_ASSERT_FALSE(logHasReserve(128*1024,64*1024+1));TEST_ASSERT_FALSE(logHasReserve(64*1024,64*1024));}
void storage_contract(){TEST_ASSERT_EQUAL_STRING("littlefs",LITTLEFS_PARTITION_LABEL);TEST_ASSERT_EQUAL(503,storageLogsHttpStatus(false));TEST_ASSERT_EQUAL(200,storageLogsHttpStatus(true));TEST_ASSERT_EQUAL_INT((int)StorageError::LOGGER_OPEN_FAILED,(int)loggerInitializationError(true,false,false,false));TEST_ASSERT_EQUAL_INT((int)StorageError::HEADER_WRITE_FAILED,(int)loggerInitializationError(true,true,false,false));TEST_ASSERT_EQUAL_INT((int)StorageError::NONE,(int)loggerInitializationError(true,true,true,true));TEST_ASSERT_TRUE(activeLogMatches("/M-1.dmslog","/M-1.dmslog",true));TEST_ASSERT_FALSE(activeLogMatches("/M-1.dmslog","/M-2.dmslog",true));TEST_ASSERT_TRUE(safeLogBasename("M-00000001.dmslog"));TEST_ASSERT_FALSE(safeLogBasename("../x.dmslog"));TEST_ASSERT_FALSE(safeLogBasename("folder/x.dmslog"));TEST_ASSERT_FALSE(safeLogBasename("x.csv"));}
void raw_policy(){RawFramePolicy s;uint8_t a[]={1,2,3},b[]={1,2,4};TEST_ASSERT_TRUE(shouldStoreRaw(s,a,3,1));TEST_ASSERT_FALSE(shouldStoreRaw(s,a,3,1000));TEST_ASSERT_TRUE(shouldStoreRaw(s,b,3,1001));TEST_ASSERT_TRUE(shouldStoreRaw(s,b,3,61002));TEST_ASSERT_TRUE(shouldStoreRaw(s,b,3,61003,true));}
void register_bank(){BmsSnapshot s;s.sequence=0x12345678;s.basic.voltage_mV=80000;s.cells.count=1;s.cells.mV[0]=3333;RegisterBank b;b.update(s,50,0);uint16_t r[256];TEST_ASSERT_TRUE(b.read(0,256,r,256));TEST_ASSERT_EQUAL_HEX16(r[0],r[254]);TEST_ASSERT_EQUAL_HEX16(r[1],r[255]);TEST_ASSERT_EQUAL(3333,r[64]);}
int main(){UNITY_BEGIN();RUN_TEST(requests);RUN_TEST(basic);RUN_TEST(cells_reset);RUN_TEST(hardware);RUN_TEST(invalid_frames);RUN_TEST(link);RUN_TEST(snapshot_wire);RUN_TEST(rtc_epoch);RUN_TEST(log_record);RUN_TEST(log_header);RUN_TEST(log_storage_policy);RUN_TEST(storage_contract);RUN_TEST(raw_policy);RUN_TEST(register_bank);return UNITY_END();}
