#include "JbdCodec.h"
#include <string.h>
namespace dms {
static uint16_t be16(const uint8_t*p){return uint16_t(p[0])<<8|p[1];}
uint16_t jbdChecksum(const uint8_t*d,size_t n){uint32_t s=0;while(n--)s+=*d++;return uint16_t(0u-s);}
size_t encodeJbdRead(uint8_t c,uint8_t*out,size_t cap){if(cap<7)return 0;out[0]=0xDD;out[1]=0xA5;out[2]=c;out[3]=0;uint16_t x=jbdChecksum(out+2,2);out[4]=x>>8;out[5]=x;out[6]=0x77;return 7;}
size_t encodeJbdError(uint8_t c,uint8_t s,uint8_t*out,size_t cap){if(cap<7)return 0;out[0]=0xDD;out[1]=c;out[2]=s;out[3]=0;uint16_t x=jbdChecksum(out+2,2);out[4]=x>>8;out[5]=x;out[6]=0x77;return 7;}
JbdResult validateJbdRequest(const uint8_t*d,size_t n,JbdFrame*out){if(n<7)return JbdResult::INCOMPLETE;if(d[0]!=0xDD)return JbdResult::BAD_START;if(d[1]!=0xA5&&d[1]!=0x5A)return JbdResult::BAD_ACTION;size_t z=size_t(d[3])+7;if(z!=n||z>JBD_MAX_FRAME)return JbdResult::BAD_LENGTH;if(d[n-1]!=0x77)return JbdResult::BAD_END;if(be16(d+n-3)!=jbdChecksum(d+2,n-5))return JbdResult::BAD_CHECKSUM;if(out){*out=JbdFrame{};memcpy(out->bytes,d,n);out->size=n;out->command=d[2];out->payloadLength=d[3];}return JbdResult::OK;}
JbdResult validateJbdResponse(const uint8_t*d,size_t n,uint8_t expected,JbdFrame*out){if(n<7)return JbdResult::INCOMPLETE;if(d[0]!=0xDD)return JbdResult::BAD_START;size_t z=size_t(d[3])+7;if(z!=n||z>JBD_MAX_FRAME)return JbdResult::BAD_LENGTH;if(d[n-1]!=0x77)return JbdResult::BAD_END;if(d[1]!=expected)return JbdResult::BAD_COMMAND;if(be16(d+n-3)!=jbdChecksum(d+2,n-5))return JbdResult::BAD_CHECKSUM;if(d[2])return JbdResult::BAD_STATUS;if(out){*out=JbdFrame{};memcpy(out->bytes,d,n);out->size=n;out->command=d[1];out->status=d[2];out->payloadLength=d[3];}return JbdResult::OK;}
bool decodeBasic(const JbdFrame&f,BasicInfo&o){o=BasicInfo{};if(f.command!=3||f.payloadLength<23)return false;const uint8_t*p=f.bytes+4;o.voltage_mV=be16(p)*10u;o.current_mA=int16_t(be16(p+2))*10;o.remaining_mAh=be16(p+4)*10u;o.nominal_mAh=be16(p+6)*10u;o.power_mW=int64_t(o.voltage_mV)*o.current_mA/1000;o.cycles=be16(p+8);o.productionRaw=be16(p+10);o.day=o.productionRaw&31;o.month=(o.productionRaw>>5)&15;o.year=2000+(o.productionRaw>>9);o.balanceLow=be16(p+12);o.balanceHigh=be16(p+14);o.protection=be16(p+16);o.softwareMajor=p[18]>>4;o.softwareMinor=p[18]&15;o.rsoc=p[19];o.fets=p[20];o.cellCount=p[21];o.ntcCount=p[22];if(o.ntcCount>8||23u+2u*o.ntcCount>f.payloadLength){o=BasicInfo{};return false;}for(uint8_t i=0;i<o.ntcCount;i++)o.temperatures_dC[i]=int16_t(be16(p+23+2*i))-2731;size_t x=23+2*o.ntcCount;o.extraLength=(f.payloadLength-x>32)?32:f.payloadLength-x;memcpy(o.extra,p+x,o.extraLength);return true;}
bool decodeCells(const JbdFrame&f,CellInfo&o){o=CellInfo{};if(f.command!=4||!f.payloadLength||(f.payloadLength&1))return false;uint8_t n=f.payloadLength/2;if(n>32)return false;o.count=n;o.minimum_mV=0xFFFF;uint32_t sum=0;for(uint8_t i=0;i<n;i++){uint16_t v=be16(f.bytes+4+2*i);o.mV[i]=v;sum+=v;if(v<o.minimum_mV){o.minimum_mV=v;o.minIndex=i+1;}if(v>o.maximum_mV){o.maximum_mV=v;o.maxIndex=i+1;}}o.average_mV=sum/n;o.delta_mV=o.maximum_mV-o.minimum_mV;return true;}
bool decodeHardware(const JbdFrame&f,char*out,size_t cap){if(!out||!cap||f.command!=5||f.payloadLength>31)return false;size_t n=f.payloadLength<cap-1?f.payloadLength:cap-1;for(size_t i=0;i<n;i++){uint8_t c=f.bytes[4+i];if(c<0x20||c>0x7E)return false;out[i]=char(c);}out[n]=0;return true;}
void JbdStreamParser::reset(){n_=expected_=0;}
bool JbdStreamParser::push(uint8_t x,uint8_t expected,JbdFrame&out,JbdResult&err){if(!n_){if(x!=0xDD)return false;b_[n_++]=x;return false;}if(n_>=JBD_MAX_FRAME){err=JbdResult::BAD_LENGTH;reset();if(x==0xDD)b_[n_++]=x;return false;}b_[n_++]=x;if(n_==4){expected_=uint16_t(b_[3])+7;if(expected_>JBD_MAX_FRAME){err=JbdResult::BAD_LENGTH;reset();return false;}}if(expected_&&n_==expected_){err=validateJbdResponse(b_,n_,expected,&out);reset();return err==JbdResult::OK;}return false;}
bool JbdStreamParser::push(uint8_t x,JbdFrame&out,JbdResult&err){return push(x,n_>1?b_[1]:0,out,err);}
}
