#include "WebPortal.h"
#ifdef ARDUINO
#include "LogFormat.h"
#include "DmsLink.h"
#include <WiFi.h>
#include <LittleFS.h>
#include <esp_system.h>
namespace dms {
static const char PAGE[] PROGMEM=R"(<html><meta name=viewport content='width=device-width'><style>body{font:16px sans-serif;max-width:960px;margin:auto;background:#111;color:#eee}table{border-collapse:collapse}td{padding:5px;border:1px solid #555}</style><h1>DMS Portable Logger</h1><button onclick='fetch("/api/time",{method:"POST",body:Date.now()})'>Sincronizar relógio</button><pre id=s></pre><div id=c></div><script>async function u(){let x=await(await fetch('/api/live')).json();s.textContent=JSON.stringify(x,null,2);c.innerHTML='<table><tr>'+((x.cells||[]).map((v,i)=>'<td>'+(i+1)+'<br>'+v+' mV</td>').join(''))+'</tr></table>'}setInterval(u,1000);u()</script></html>)";
bool WebPortal::safe(const String&n)const{return n.length()>1&&n.startsWith("/")&&n.indexOf("..")<0&&n.indexOf('\\')<0&&n.endsWith(".dmslog");}
bool WebPortal::begin(const char*r,uint8_t ch,const char*pw,SnapshotStore&s,BinaryLogger&l,RtcClock&rtc){role_=r;store_=&s;logger_=&l;rtc_=&rtc;snprintf(ssid_,sizeof ssid_,"DMS-%sLogger-%04X",r,uint16_t(ESP.getEfuseMac()));WiFi.mode(WIFI_AP);if(!WiFi.softAP(ssid_,pw,ch))return false;server_.on("/",[this]{root();});server_.on("/api/status",[this]{status();});server_.on("/api/live",[this]{live();});server_.on("/api/logs",HTTP_GET,[this]{logs();});server_.on("/api/time",HTTP_POST,[this]{setTime();});server_.on("/api/session/rotate",HTTP_POST,[this]{rotate();});server_.on("/api/logs/erase-all",HTTP_POST,[this]{eraseAll();});server_.onNotFound([this]{if(server_.uri().startsWith("/api/logs/")){if(server_.method()==HTTP_DELETE)removeOne();else if(server_.uri().endsWith("/csv"))csv();else fileDownload();}else server_.send(404,"text/plain","not found");});server_.begin();return true;}
void WebPortal::handle(){server_.handleClient();}void WebPortal::root(){server_.send_P(200,"text/html",PAGE);}
void WebPortal::status(){const auto&s=logger_->stats();String j="{\"role\":\""+String(role_)+"\",\"ssid\":\""+ssid_+"\",\"uptime_ms\":"+millis()+",\"flash_bytes\":"+ESP.getFlashChipSize()+",\"expected_flash_bytes\":4194304,\"flash_mismatch\":"+(ESP.getFlashChipSize()!=4194304?"true":"false")+",\"reset_reason\":"+esp_reset_reason()+",\"clock_quality\":"+uint8_t(rtc_->quality())+",\"fs_total\":"+LittleFS.totalBytes()+",\"fs_used\":"+LittleFS.usedBytes()+",\"fs_free\":"+(LittleFS.totalBytes()-LittleFS.usedBytes())+",\"bytes_per_second\":"+s.bytesPerSecond+",\"estimated_minutes_remaining\":"+s.estimatedMinutesRemaining+",\"logging\":"+(s.running?"true":"false")+",\"dropped\":"+s.dropped+"}";server_.send(200,"application/json",j);}
void WebPortal::live(){BmsSnapshot s;if(!store_->latest(s)){server_.send(503,"application/json","{\"error\":\"no_snapshot\"}");return;}String j="{\"seq\":"+String(s.sequence)+",\"timestamp_ms\":"+String((unsigned long long)s.timestampUtcMs)+",\"age_ms\":"+(millis()-s.captureMonotonicMs)+",\"quality\":"+s.quality+",\"pack_mV\":"+s.basic.voltage_mV+",\"current_mA\":"+s.basic.current_mA+",\"power_mW\":"+String((long long)s.basic.power_mW)+",\"rmcap_mAh\":"+s.basic.remaining_mAh+",\"nominal_mAh\":"+s.basic.nominal_mAh+",\"rsoc\":"+s.basic.rsoc+",\"fets\":"+s.basic.fets+",\"protection\":"+s.basic.protection+",\"balance_low\":"+s.basic.balanceLow+",\"balance_high\":"+s.basic.balanceHigh+",\"hardware\":\""+String(s.hardware)+"\",\"poll_us\":"+s.pollDurationUs+",\"timeouts\":"+s.timeouts+",\"checksum_errors\":"+s.checksumErrors+",\"link_errors\":"+s.linkErrors+",\"panel_requests\":"+s.panelRequests+",\"proxy_requests\":"+s.proxyRequests+",\"cache_responses\":"+s.cacheResponses+",\"write_blocked\":"+s.writeBlocked+",\"last_panel_command\":"+s.lastPanelCommand+",\"last_panel_flags\":"+s.lastPanelFlags+",\"last_panel_latency_ms\":"+s.lastPanelLatencyMs+",\"source_age_ms\":"+s.sourceAgeMs+",\"min_mV\":"+s.cells.minimum_mV+",\"max_mV\":"+s.cells.maximum_mV+",\"delta_mV\":"+s.cells.delta_mV+",\"average_mV\":"+s.cells.average_mV+",\"temperatures_dC\":[";for(uint8_t i=0;i<s.basic.ntcCount;i++){if(i)j+=',';j+=s.basic.temperatures_dC[i];}j+="],\"cells\":[";for(uint8_t i=0;i<s.cells.count;i++){if(i)j+=',';j+=s.cells.mV[i];}j+="]}";server_.send(200,"application/json",j);}
void WebPortal::logs(){String j="[";File root=LittleFS.open("/");File f=root.openNextFile();bool first=true;while(f){String n=f.name();if(n.endsWith(".dmslog")){if(!first)j+=',';j+="{\"name\":\""+n+"\",\"size\":"+f.size()+"}";first=false;}f.close();f=root.openNextFile();}j+="]";server_.send(200,"application/json",j);}
void WebPortal::fileDownload(){String n=server_.uri().substring(9);if(!n.startsWith("/"))n="/"+n;if(!safe(n)||!LittleFS.exists(n)){server_.send(404);return;}File f=LittleFS.open(n,FILE_READ);server_.streamFile(f,"application/octet-stream");f.close();}
void WebPortal::csv(){String n=server_.uri().substring(9);n.remove(n.length()-4);if(!n.startsWith("/"))n="/"+n;if(!safe(n)||!LittleFS.exists(n)){server_.send(404);return;}File f=LittleFS.open(n,FILE_READ);if(!f||f.size()<64){server_.send(400);return;}f.seek(64);server_.setContentLength(CONTENT_LENGTH_UNKNOWN);server_.send(200,"text/csv","record_type,timestamp_ms,monotonic_ms,sequence,age_ms,quality,pack_mV,current_mA,power_mW,rmcap_mAh,nominal_mAh,rsoc,fets,cells_mV\n");uint8_t h[8],payload[256],crc[4];while(f.read(h,8)==8){uint16_t sync=h[0]|uint16_t(h[1])<<8;uint8_t type=h[2];uint32_t len=h[4]|uint32_t(h[5])<<8|uint32_t(h[6])<<16|uint32_t(h[7])<<24;if(sync!=LOG_SYNC||len>sizeof payload||f.read(payload,len)!=len||f.read(crc,4)!=4)break;if(type==1||type==3){BmsSnapshot s;uint32_t age;if(deserializeSample(payload,len,s,age)){String row=type==1?"MASTER_SAMPLE,":"SLAVE_SAMPLE,";row+=String((unsigned long long)s.timestampUtcMs)+","+s.captureMonotonicMs+","+s.sequence+","+age+","+s.quality+","+s.basic.voltage_mV+","+s.basic.current_mA+","+String((long long)s.basic.power_mW)+","+s.basic.remaining_mAh+","+s.basic.nominal_mAh+","+s.basic.rsoc+","+s.basic.fets+",\"";for(uint8_t i=0;i<s.cells.count;i++){if(i)row+=';';row+=s.cells.mV[i];}row+="\"\n";server_.sendContent(row);vTaskDelay(1);}}}f.close();server_.sendContent("");}
void WebPortal::setTime(){uint64_t epoch=strtoull(server_.arg("plain").c_str(),nullptr,10),old=0;rtc_->read(old);bool ok=rtc_->write(epoch,ClockQuality::BROWSER_SET);if(ok){uint8_t event[17],*p=event;put64(p,old);put64(p,epoch);*p++=uint8_t(ClockQuality::BROWSER_SET);logger_->append(LogType::TIME_EVENT,event,p-event);if(old&&epoch<old)ok=logger_->rotate();}server_.send(ok?200:400,"application/json","{}");}
void WebPortal::rotate(){server_.send(logger_->rotate()?200:500,"application/json","{}");}
void WebPortal::removeOne(){String n=server_.uri().substring(9);if(!n.startsWith("/"))n="/"+n;server_.send(safe(n)&&n!=logger_->name()&&LittleFS.remove(n)?200:400,"application/json","{}");}
void WebPortal::eraseAll(){if(server_.arg("plain")!="ERASE-ALL"){server_.send(400,"application/json","{\"error\":\"confirmation\"}");return;}File root=LittleFS.open("/");File f=root.openNextFile();while(f){String n=f.name();f.close();if(safe(n)&&n!=logger_->name())LittleFS.remove(n);f=root.openNextFile();}server_.send(200,"application/json","{}");}}
#endif
